name: flutter_admain_center
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_localizations:
        sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_secure_storage: ^9.2.4
  firebase_core: ^4.0.0 
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  sqflite: ^2.3.0 # استخدم أحدث إصدار
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2 # للتحقق من وجود اتصال بالإنترنت 
  provider: ^6.1.5
  sembast: ^3.8.5+1
  collection: ^1.19.1
  fl_chart: ^1.0.0
  dartz: ^0.10.1
  app_links: ^6.4.0
  excel: ^4.0.6
  # share_plus: ^7.2.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  open_filex: ^4.7.0
  
  #shared_preferences: ^2.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
