// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG-qBkANIUOvie_xgLVytlrXsOXs63h4U',
    appId: '1:834298176433:web:6a3096f8d988e13708d390',
    messagingSenderId: '834298176433',
    projectId: 'centers-d69e9',
    authDomain: 'centers-d69e9.firebaseapp.com',
    storageBucket: 'centers-d69e9.firebasestorage.app',
    measurementId: 'G-WE9SRB5ZSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7wTtOp3heU9ztkhKXUlPfTnlOVlA7E6w',
    appId: '1:834298176433:android:8d2fe6ea65e0d60608d390',
    messagingSenderId: '834298176433',
    projectId: 'centers-d69e9',
    storageBucket: 'centers-d69e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMGoLH6sKBcEdGy2nUBMO5vDWR1rFAouw',
    appId: '1:834298176433:ios:f046d73fe8c7f9c608d390',
    messagingSenderId: '834298176433',
    projectId: 'centers-d69e9',
    storageBucket: 'centers-d69e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdmainCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMGoLH6sKBcEdGy2nUBMO5vDWR1rFAouw',
    appId: '1:834298176433:ios:f046d73fe8c7f9c608d390',
    messagingSenderId: '834298176433',
    projectId: 'centers-d69e9',
    storageBucket: 'centers-d69e9.firebasestorage.app',
    iosBundleId: 'com.example.flutterAdmainCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG-qBkANIUOvie_xgLVytlrXsOXs63h4U',
    appId: '1:834298176433:web:a337003865a06aed08d390',
    messagingSenderId: '834298176433',
    projectId: 'centers-d69e9',
    authDomain: 'centers-d69e9.firebaseapp.com',
    storageBucket: 'centers-d69e9.firebasestorage.app',
    measurementId: 'G-T1D780K4QB',
  );
}
